export default [
  {
    id: '33',
    pid: null,
    name: '浙江省',
    type: null,
    tag: '0',
    children: [
      {
        id: '3301',
        pid: '33',
        name: '杭州市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330100',
            pid: '3301',
            name: '市区',
            type: null,
            tag: '2',
            children: [],
          },
          {
            id: '330101',
            pid: '3301',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330102',
            pid: '3301',
            name: '上城区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330105',
            pid: '3301',
            name: '拱墅区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330106',
            pid: '3301',
            name: '西湖区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330108',
            pid: '3301',
            name: '滨江区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330109',
            pid: '3301',
            name: '萧山区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330110',
            pid: '3301',
            name: '余杭区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330111',
            pid: '3301',
            name: '富阳区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330112',
            pid: '3301',
            name: '临安区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330113',
            pid: '3301',
            name: '临平区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330114',
            pid: '3301',
            name: '钱塘区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330122',
            pid: '3301',
            name: '桐庐县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330127',
            pid: '3301',
            name: '淳安县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330150',
            pid: '3301',
            name: '杭州西湖风景名胜区管理委员会',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330152',
            pid: '3301',
            name: '杭州之江国家旅游度假区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330153',
            pid: '3301',
            name: '经济技术开发区(杭州出口加工区)',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330182',
            pid: '3301',
            name: '建德市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3302',
        pid: '33',
        name: '宁波市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330200',
            pid: '3302',
            name: '市区',
            type: null,
            tag: '2',
            children: [],
          },
          {
            id: '330201',
            pid: '3302',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330203',
            pid: '3302',
            name: '海曙区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330205',
            pid: '3302',
            name: '江北区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330206',
            pid: '3302',
            name: '北仑区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330211',
            pid: '3302',
            name: '镇海区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330212',
            pid: '3302',
            name: '鄞州区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330213',
            pid: '3302',
            name: '奉化区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330225',
            pid: '3302',
            name: '象山县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330226',
            pid: '3302',
            name: '宁海县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330251',
            pid: '3302',
            name: '大榭开发区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330252',
            pid: '3302',
            name: '杭州湾新区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330253',
            pid: '3302',
            name: '梅山保税港区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330254',
            pid: '3302',
            name: '高新区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330255',
            pid: '3302',
            name: '保税区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330256',
            pid: '3302',
            name: '东钱湖旅游度假区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330257',
            pid: '3302',
            name: '石化经济技术开发区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330258',
            pid: '3302',
            name: '宁波临空经济示范区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330281',
            pid: '3302',
            name: '余姚市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330282',
            pid: '3302',
            name: '慈溪市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3303',
        pid: '33',
        name: '温州市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330300',
            pid: '3303',
            name: '市区',
            type: null,
            tag: '2',
            children: [],
          },
          {
            id: '330301',
            pid: '3303',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330302',
            pid: '3303',
            name: '鹿城区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330303',
            pid: '3303',
            name: '龙湾区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330304',
            pid: '3303',
            name: '瓯海区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330305',
            pid: '3303',
            name: '洞头区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330324',
            pid: '3303',
            name: '永嘉县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330326',
            pid: '3303',
            name: '平阳县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330327',
            pid: '3303',
            name: '苍南县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330328',
            pid: '3303',
            name: '文成县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330329',
            pid: '3303',
            name: '泰顺县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330351',
            pid: '3303',
            name: '浙南产业集聚区（经开区）',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330353',
            pid: '3303',
            name: '温州浙南科技城管理委员会',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330354',
            pid: '3303',
            name: '生态园管理委员会',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330355',
            pid: '3303',
            name: '瓯江口产业集聚区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330381',
            pid: '3303',
            name: '瑞安市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330382',
            pid: '3303',
            name: '乐清市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330383',
            pid: '3303',
            name: '龙港市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3304',
        pid: '33',
        name: '嘉兴市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330401',
            pid: '3304',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330402',
            pid: '3304',
            name: '南湖区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330411',
            pid: '3304',
            name: '秀洲区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330421',
            pid: '3304',
            name: '嘉善县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330424',
            pid: '3304',
            name: '海盐县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330451',
            pid: '3304',
            name: '嘉兴经济技术开发区（国际商务区）',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330452',
            pid: '3304',
            name: '嘉兴港区开发建设管理委员会',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330481',
            pid: '3304',
            name: '海宁市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330482',
            pid: '3304',
            name: '平湖市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330483',
            pid: '3304',
            name: '桐乡市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3305',
        pid: '33',
        name: '湖州市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330501',
            pid: '3305',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330502',
            pid: '3305',
            name: '吴兴区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330503',
            pid: '3305',
            name: '南浔区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330521',
            pid: '3305',
            name: '德清县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330522',
            pid: '3305',
            name: '长兴县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330523',
            pid: '3305',
            name: '安吉县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330552',
            pid: '3305',
            name: '湖州南太湖新区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330553',
            pid: '3305',
            name: '湖州莫干山高新技术产业开发区',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3306',
        pid: '33',
        name: '绍兴市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330600',
            pid: '3306',
            name: '市区',
            type: null,
            tag: '2',
            children: [],
          },
          {
            id: '330601',
            pid: '3306',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330602',
            pid: '3306',
            name: '越城区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330603',
            pid: '3306',
            name: '柯桥区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330604',
            pid: '3306',
            name: '上虞区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330624',
            pid: '3306',
            name: '新昌县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330652',
            pid: '3306',
            name: '绍兴滨海新城',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330654',
            pid: '3306',
            name: '镜湖新区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330681',
            pid: '3306',
            name: '诸暨市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330683',
            pid: '3306',
            name: '嵊州市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3307',
        pid: '33',
        name: '金华市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330701',
            pid: '3307',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330702',
            pid: '3307',
            name: '婺城区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330703',
            pid: '3307',
            name: '金东区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330723',
            pid: '3307',
            name: '武义县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330726',
            pid: '3307',
            name: '浦江县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330727',
            pid: '3307',
            name: '磐安县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330751',
            pid: '3307',
            name: '经济技术开发区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330752',
            pid: '3307',
            name: '金义都市新区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330753',
            pid: '3307',
            name: '金华山旅游经济区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330781',
            pid: '3307',
            name: '兰溪市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330782',
            pid: '3307',
            name: '义乌市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330783',
            pid: '3307',
            name: '东阳市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330784',
            pid: '3307',
            name: '永康市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3308',
        pid: '33',
        name: '衢州市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330800',
            pid: '3308',
            name: '市区',
            type: null,
            tag: '2',
            children: [],
          },
          {
            id: '330801',
            pid: '3308',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330802',
            pid: '3308',
            name: '柯城区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330803',
            pid: '3308',
            name: '衢江区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330822',
            pid: '3308',
            name: '常山县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330824',
            pid: '3308',
            name: '开化县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330825',
            pid: '3308',
            name: '龙游县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330851',
            pid: '3308',
            name: '衢州绿色产业集聚区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330852',
            pid: '3308',
            name: '西区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330881',
            pid: '3308',
            name: '江山市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3309',
        pid: '33',
        name: '舟山市',
        type: null,
        tag: '0',
        children: [
          {
            id: '330901',
            pid: '3309',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '330902',
            pid: '3309',
            name: '定海区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330903',
            pid: '3309',
            name: '普陀区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330921',
            pid: '3309',
            name: '岱山县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330922',
            pid: '3309',
            name: '嵊泗县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330951',
            pid: '3309',
            name: '海洋产业集聚区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330952',
            pid: '3309',
            name: '新城管委会',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330953',
            pid: '3309',
            name: '普陀山-朱家尖管委会(普陀山管委会)',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '330955',
            pid: '3309',
            name: '六横管委会',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3310',
        pid: '33',
        name: '台州市',
        type: null,
        tag: '0',
        children: [
          {
            id: '331001',
            pid: '3310',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '331002',
            pid: '3310',
            name: '椒江区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331003',
            pid: '3310',
            name: '黄岩区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331004',
            pid: '3310',
            name: '路桥区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331022',
            pid: '3310',
            name: '三门县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331023',
            pid: '3310',
            name: '天台县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331024',
            pid: '3310',
            name: '仙居县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331051',
            pid: '3310',
            name: '经济开发区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331052',
            pid: '3310',
            name: '台州湾新区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331081',
            pid: '3310',
            name: '温岭市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331082',
            pid: '3310',
            name: '临海市',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331083',
            pid: '3310',
            name: '玉环市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
      {
        id: '3311',
        pid: '33',
        name: '丽水市',
        type: null,
        tag: '0',
        children: [
          {
            id: '331101',
            pid: '3311',
            name: '市本级',
            type: null,
            tag: '1',
            children: [],
          },
          {
            id: '331102',
            pid: '3311',
            name: '莲都区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331121',
            pid: '3311',
            name: '青田县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331122',
            pid: '3311',
            name: '缙云县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331123',
            pid: '3311',
            name: '遂昌县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331124',
            pid: '3311',
            name: '松阳县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331125',
            pid: '3311',
            name: '云和县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331126',
            pid: '3311',
            name: '庆元县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331127',
            pid: '3311',
            name: '景宁畲族自治县',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331151',
            pid: '3311',
            name: '经济开发区',
            type: null,
            tag: '0',
            children: [],
          },
          {
            id: '331181',
            pid: '3311',
            name: '龙泉市',
            type: null,
            tag: '0',
            children: [],
          },
        ],
      },
    ],
  },
]
